# Generated by Django 4.1.3 on 2022-11-21 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_img', models.ImageField(upload_to='event_drink_pics')),
                ('drink_name', models.CharField(max_length=50, null=True)),
                ('drink_price', models.IntegerField(default=0)),
                ('drink_time', models.TimeField(default=datetime.datetime(2022, 11, 21, 16, 39, 38, 215910, tzinfo=datetime.timezone.utc))),
                ('drink_from_date', models.DateField(default=datetime.date(2022, 11, 21))),
                ('drink_to_date', models.DateField(default=datetime.date(2022, 11, 21))),
            ],
        ),
        migrations.CreateModel(
            name='DrinkGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_img', models.ImageField(upload_to='drink_pics')),
                ('drink_name', models.CharField(max_length=50, null=True)),
                ('drink_slug', models.SlugField(null=True, unique=True)),
                ('drink_price', models.IntegerField(default=0)),
                ('drink_desc', models.TextField()),
                ('drink_allergic', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_img', models.ImageField(upload_to='event_food_pics')),
                ('food_name', models.CharField(max_length=50, null=True)),
                ('food_price', models.IntegerField(default=0)),
                ('food_time', models.TimeField(default=datetime.datetime(2022, 11, 21, 16, 39, 38, 215910, tzinfo=datetime.timezone.utc))),
                ('food_from_date', models.DateField(default=datetime.date(2022, 11, 21))),
                ('food_to_date', models.DateField(default=datetime.date(2022, 11, 21))),
            ],
        ),
        migrations.CreateModel(
            name='FoodGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_img', models.ImageField(upload_to='food_pics')),
                ('food_name', models.CharField(max_length=50, null=True)),
                ('food_slug', models.SlugField(null=True, unique=True)),
                ('food_price', models.IntegerField(default=0)),
                ('food_desc', models.TextField()),
                ('food_allergic', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_img', models.ImageField(blank=True, default='review_pics/default-user.png', null=True, upload_to='review_pics')),
                ('review_name', models.CharField(max_length=100, null=True)),
                ('review_text', models.TextField()),
                ('review_date', models.DateField(default=datetime.date(2022, 11, 21))),
                ('review_time', models.TimeField(default=datetime.datetime(2022, 11, 21, 16, 39, 38, 216878, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_email', models.EmailField(max_length=254)),
                ('subscribe_date', models.DateField(default=datetime.date(2022, 11, 21))),
                ('subscribe_time', models.TimeField(default=datetime.datetime(2022, 11, 21, 16, 39, 38, 216878, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
